### ISSUE TITLE
Implement Binary Search

### ISSUE THREAD

**Issue by KanishkKhurana** [dsc-gtbit/HACKTOBERFEST21-GTBIT-ML#15]
complete the program given in the following directory -> \
`Beginner/searching and sorting/binary_search.py`

**Comment by Manas146** [comment]
i would like to work on this issue.

**Comment by KanishkKhurana** [comment]
@Manas146 we appreciate your interest, but let's give others a chance here as well.

**Comment by AmanRana10** [comment]
i would like to work on this issue

**Comment by KanishkKhurana** [comment]
sure @AmanRana10 , go ahead
